/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./src/**/*.{js,ts,jsx,tsx,html}'],
    daisyui: {
        themes: [
            'cupcake',
            'bumblebee',
            'retro',
            'valentine',
            'halloween',
            'garden',
            'lofi',
            'pastel',
            'dracula',
            'cmyk',
            'autumn',
            'business',
            'acid',
            'coffee',
            'winter',
            'dim',
            'nord',
            'sunset',
            {
                'lesi-default': {
                    primary: '#131c26',
                    'primary-content': '#fff',
                    secondary: '#cc3369',
                    'secondary-content': '#fff',
                    accent: '#cc3369',
                    'accent-content': '#fff',
                    neutral: '#181818',
                    'neutral-content': '#cbcbcb',
                    'base-100': '#1f2429',
                    'base-200': '#151a1f',
                    'base-300': '#111519',
                    'base-content': '#dddddd',
                    info: '#0088a6',
                    'info-content': '#00060a',
                    success: '#29c840',
                    'success-content': '#001603',
                    warning: '#febc2e',
                    'warning-content': '#160200',
                    error: '#ff5f57',
                    'error-content': '#160004',
                },
            },
            {
                gear5: {
                    primary: '#8868aa',
                    'primary-content': '#f1f1f1',
                    secondary: '#ebc965',
                    'secondary-content': '#010103',
                    accent: '#b73f5c',
                    'accent-content': '#f1f1f1',
                    neutral: '#97866a',
                    'neutral-content': '#cbcbcb',
                    'base-100': '#f9f9f9',
                    'base-200': '#e7ebec',
                    'base-300': '#cbd3e0',
                    'base-content': '#161615',
                    info: '#019bd9',
                    'info-content': '#fefbff',
                    success: '#7bd53d',
                    'success-content': '#010103',
                    warning: '#fbb329',
                    'warning-content': '#2a1500',
                    error: '#ed281e',
                    'error-content': '#fffcf3',
                },
            },
            {
                naruto: {
                    primary: '#11396b',
                    'primary-content': '#f1f1f1',
                    secondary: '#e2e23e',
                    'secondary-content': '#010103',
                    accent: '#f67b30',
                    'accent-content': '#f1f1f1',
                    neutral: '#97866a',
                    'neutral-content': '#cbcbcb',
                    'base-100': '#f3f3f3',
                    'base-200': '#eb8e45',
                    'base-300': '#b23b24',
                    'base-content': '#2a2818',
                    info: '#11396b',
                    'info-content': '#fefbff',
                    success: '#348855',
                    'success-content': '#010103',
                    warning: '#e2e23e',
                    'warning-content': '#2a1500',
                    error: '#b23b24',
                    'error-content': '#fffcf3',
                },
            },
        ],
        styled: false,
    },
    theme: {
        screens: {
            sm: '480px',
            md: '768px',
            lg: '976px',
            xl: '1440px',
        },
        extend: {
            animation: {
                'spin-slow': 'spin 5s linear infinite',
            },
            colors: {
                twitchPurple: '#9146ff',
            },
            fontFamily: {
                teko: ['Teko', 'sans-serif'],
                inter: ['Inter', 'sans-serif'],
            },
            backgroundImage: {
                checkMark: 'url(/_static/images/icons/checkmark.svg)',
            },
            spacing: {
                '50%': '50%',
                '90%': '90%',
                '47px': '47px',
            },
            boxShadow: {
                '3xl': '0 35px 60px -15px rgba(0, 0, 0, 1)',
            },
            width: {
                '1/2': '50%',
                '1/3': '33.333%',
                '2/3': '66.667%',
                '1/4': '25%',
                '2/4': '50%',
                '3/4': '75%',
                '1/12': '8.333%',
                '2/12': '16.667%',
                '3/12': '25%',
                '4/12': '33.333%',
                '5/12': '41.667%',
                '6/12': '50%',
                '7/12': '58.333%',
                '8/12': '66.667%',
                '9/12': '75%',
                '10/12': '83.333%',
                '11/12': '91.667%',
            },
            height: {
                '1/2': '50%',
                '1/3': '33.333%',
                '2/3': '66.667%',
                '1/4': '25%',
                '2/4': '50%',
                '3/4': '75%',
                '1/12': '8.333%',
                '2/12': '16.667%',
                '3/12': '25%',
                '4/12': '33.333%',
                '5/12': '41.667%',
                '6/12': '50%',
                '7/12': '58.333%',
                '8/12': '66.667%',
                '9/12': '75%',
                '10/12': '83.333%',
                '11/12': '91.667%',
            },
            screens: {
                xs: '420px',
                sm: '640px',
                md: '768px',
                lg: '1024px',
                xl: '1280px',
                '2xl': '1536px',
                '3xl': '1745.45px',
                '4xl': '1920px',
                '5xl': '2133.33px',
                '6xl': '2400px',
                '7xl': '2560px',
                '8xl': '2880px',
                '9xl': '3840px',
                '10xl': '5760px',
                '11xl': '7680px',
            },
        },
    },
    plugins: [require('daisyui')],
};
