export { Home } from "./home/home";
export { Error404 } from "./404/404";
export { AspectRatio } from "./aspect-ratio-calculator/aspect-ratio";
export { VideoToMp3 } from "./video-editor/video-mp3/video-to-mp3";
export { Settings } from "./settings/settings";
export { CropToShort } from "./video-editor/crop-to-shorts/crop-to-shorts";
export { VideoEditor } from "./video-editor/video-editor/video-editor";
export { PdfToPng } from "./pdf-tools/pdf-to-png/pdf-to-png";
export { PasswordGenerator } from "./password-generator/password-generator";
export { WeightConverter } from "./weight-converter/weight-converter";
export { IconConverter } from "./icon-converter/icon-converter";
export { Minifier } from "./minifier/minifier";
export { Privacy } from "./privacy/privacy"