
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = "heap";
create extension if not exists pgcrypto;

COMMENT ON SCHEMA "public" IS 'standard public schema';


CREATE TABLE IF NOT EXISTS "public"."aim_trainer" (
    "id" bigint NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "username" "text" DEFAULT ''::"text" NOT NULL,
    "score" real DEFAULT '0'::real,
    "accuracy" real DEFAULT '0'::real,
    "completed_rounds" integer,
    "milo_attacks" integer,
    "nice_triggers" integer
);
ALTER TABLE "public"."aim_trainer" OWNER TO "postgres";
DROP SEQUENCE if exists "public"."aim_trainer_id_seq" on "public"."aim_trainer";
ALTER TABLE "public"."aim_trainer" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."aim_trainer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."api_keys" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "access_token" "text",
    "refresh_token" "text",
    "refresh_token_expiry" bigint,
    "client_id" "text",
    "client_secret" "text",
    "base_url" "text",
    "redirect_url" "text"
);
ALTER TABLE "public"."api_keys" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_character_types" (
    "id" bigint NOT NULL,
    "character_type" character varying NOT NULL,
    "bungie_character_type_id" smallint
);
ALTER TABLE "public"."destiny_character_types" OWNER TO "postgres";
ALTER TABLE "public"."destiny_character_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."character_types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."destiny_user_characters" (
    "id" bigint NOT NULL,
    "membership_id" character varying NOT NULL,
    "character_id" character varying NOT NULL,
    "character_type" character varying,
    "minutes_played" bigint
);
ALTER TABLE "public"."destiny_user_characters" OWNER TO "postgres";
ALTER TABLE "public"."destiny_user_characters" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."characters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."countdown" (
    "id" bigint NOT NULL,
    "uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "target_date" timestamp with time zone NOT NULL,
    "message" "text" NOT NULL,
    "fallback_message" "text" NOT NULL
);
ALTER TABLE "public"."countdown" OWNER TO "postgres";
ALTER TABLE "public"."countdown" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."countdown_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."destiny_platforms" (
    "platform_id" smallint NOT NULL,
    "platform_friendly_name" character varying
);
ALTER TABLE "public"."destiny_platforms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_trials" (
    "id" bigint NOT NULL,
    "map" "text" NOT NULL,
    "loot" "text" NOT NULL,
    "start_date" timestamp without time zone NOT NULL,
    "end_date" timestamp without time zone NOT NULL,
    "week_number" bigint NOT NULL
);
ALTER TABLE "public"."destiny_trials" OWNER TO "postgres";
ALTER TABLE "public"."destiny_trials" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."destiny_trials_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."destiny_users" (
    "id" bigint NOT NULL,
    "membership_id" character varying,
    "bungie_id" character varying,
    "preferred_platform" smallint,
    "friendly_name" character varying
);
ALTER TABLE "public"."destiny_users" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."destiny_user_play_times" WITH ("security_invoker"='on') AS
 SELECT "u"."bungie_id",
    "sum"(
        CASE
            WHEN (("c"."character_type")::"text" = 'Warlock'::"text") THEN "c"."minutes_played"
            ELSE (0)::bigint
        END) AS "total_warlock_minutes",
    "sum"(
        CASE
            WHEN (("c"."character_type")::"text" = 'Hunter'::"text") THEN "c"."minutes_played"
            ELSE (0)::bigint
        END) AS "total_hunter_minutes",
    "sum"(
        CASE
            WHEN (("c"."character_type")::"text" = 'Titan'::"text") THEN "c"."minutes_played"
            ELSE (0)::bigint
        END) AS "total_titan_minutes"
   FROM ("public"."destiny_user_characters" "c"
     JOIN "public"."destiny_users" "u" ON ((("u"."membership_id")::"text" = ("c"."membership_id")::"text")))
  GROUP BY "u"."bungie_id";
ALTER TABLE "public"."destiny_user_play_times" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_weapon_kill_counts" (
    "id" bigint NOT NULL,
    "membership_id" character varying,
    "weapon_id" character varying,
    "pvp_kills" bigint,
    "pve_kills" bigint,
    "trials_kills" bigint,
    "weapon_hash" "text"
);
ALTER TABLE "public"."destiny_weapon_kill_counts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_weapons" (
    "id" "text" NOT NULL,
    "display_name" "text",
    "item_type_display_name" "text",
    "flavor_text" "text",
    "bucket_type_hash" "text",
    "tier_type_hash" "text",
    "tier_type_name" "text",
    "tier_type" integer,
    "talent_grid_hash" "text"
);
ALTER TABLE "public"."destiny_weapons" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."destiny_weapon_kill_summary" WITH ("security_invoker"='on') AS
 SELECT "u"."bungie_id",
    "w"."display_name" AS "weapon_name",
    "wkc"."pvp_kills",
    "wkc"."pve_kills",
    "wkc"."trials_kills"
   FROM (("public"."destiny_weapon_kill_counts" "wkc"
     JOIN "public"."destiny_users" "u" ON ((("u"."membership_id")::"text" = ("wkc"."membership_id")::"text")))
     JOIN "public"."destiny_weapons" "w" ON (("w"."id" = "wkc"."weapon_hash")))
  WHERE (1 = 1)
  ORDER BY ("wkc"."pvp_kills" IS NULL), "wkc"."pvp_kills" DESC, "u"."bungie_id";
ALTER TABLE "public"."destiny_weapon_kill_summary" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_weapon_perks" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "item_type" "text",
    "hash_id" "text" NOT NULL
);
ALTER TABLE "public"."destiny_weapon_perks" OWNER TO "postgres";


ALTER TABLE "public"."api_keys" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."lesi_webhooks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE "public"."destiny_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."destiny_weapon_kill_counts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."weapon_kill_counts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."destiny_weapon_perks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."weapon_perks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."aim_trainer"
    ADD CONSTRAINT "aim_trainer_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."aim_trainer"
    ADD CONSTRAINT "aim_trainer_username_key" UNIQUE ("username");
ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_name_key" UNIQUE ("name");
ALTER TABLE ONLY "public"."destiny_character_types"
    ADD CONSTRAINT "character_types_bungie_character_type_id_key" UNIQUE ("bungie_character_type_id");
ALTER TABLE ONLY "public"."destiny_character_types"
    ADD CONSTRAINT "character_types_character_type_key" UNIQUE ("character_type");
ALTER TABLE ONLY "public"."destiny_character_types"
    ADD CONSTRAINT "character_types_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "characters_character_id_key" UNIQUE ("character_id");
ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "characters_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."countdown"
    ADD CONSTRAINT "countdown_pkey" PRIMARY KEY ("id", "uuid");
ALTER TABLE ONLY "public"."destiny_trials"
    ADD CONSTRAINT "destiny_trials_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_trials"
    ADD CONSTRAINT "destiny_trials_week_number_key" UNIQUE ("week_number");
ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "lesi_webhooks_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_platforms"
    ADD CONSTRAINT "platforms_pkey" PRIMARY KEY ("platform_id");
ALTER TABLE ONLY "public"."destiny_platforms"
    ADD CONSTRAINT "platforms_platform_id_key" UNIQUE ("platform_id");
ALTER TABLE ONLY "public"."terror_goal"
    ADD CONSTRAINT "terror_goal_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "unique_membership_bungie" UNIQUE ("membership_id", "bungie_id");
ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "unique_membership_character" UNIQUE ("membership_id", "character_id");
ALTER TABLE ONLY "public"."destiny_weapon_kill_counts"
    ADD CONSTRAINT "unique_membership_weapon" UNIQUE ("membership_id", "weapon_id");
ALTER TABLE ONLY "public"."destiny_weapon_kill_counts"
    ADD CONSTRAINT "unique_user_weapon_pair" UNIQUE ("membership_id", "weapon_id");
ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("user_id");
ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_bungie_id_key" UNIQUE ("bungie_id");
ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_membership_id_key" UNIQUE ("membership_id");
ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_weapon_kill_counts"
    ADD CONSTRAINT "weapon_kill_counts_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_weapon_perks"
    ADD CONSTRAINT "weapon_perks_hash_id_key" UNIQUE ("hash_id");
ALTER TABLE ONLY "public"."destiny_weapon_perks"
    ADD CONSTRAINT "weapon_perks_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_weapons"
    ADD CONSTRAINT "weapons_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "characters_character_type_fkey" FOREIGN KEY ("character_type") REFERENCES "public"."destiny_character_types"("character_type");
ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_preferred_platform_fkey" FOREIGN KEY ("preferred_platform") REFERENCES "public"."destiny_platforms"("platform_id") ON UPDATE RESTRICT;


CREATE POLICY "Enable read access for service role" ON "public"."api_keys" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable read access for service role" ON "public"."destiny_character_types" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable read access for service role" ON "public"."destiny_platforms" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable read access for service role" ON "public"."destiny_user_characters" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable read access for service role" ON "public"."destiny_users" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable read access for service role" ON "public"."destiny_weapon_kill_counts" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable read access for service role" ON "public"."destiny_weapon_perks" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable read access for service role" ON "public"."destiny_weapons" FOR SELECT TO "service_role" USING (true);
CREATE POLICY "Enable update access for service role" ON "public"."api_keys" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable update access for service role" ON "public"."destiny_character_types" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable update access for service role" ON "public"."destiny_platforms" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable update access for service role" ON "public"."destiny_user_characters" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable update access for service role" ON "public"."destiny_users" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable update access for service role" ON "public"."destiny_weapon_kill_counts" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable update access for service role" ON "public"."destiny_weapon_perks" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable update access for service role" ON "public"."destiny_weapons" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."api_keys" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."destiny_character_types" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."destiny_platforms" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."destiny_user_characters" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."destiny_users" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."destiny_weapon_kill_counts" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."destiny_weapon_perks" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable write access for service role" ON "public"."destiny_weapons" FOR INSERT TO "service_role" WITH CHECK (true);

ALTER TABLE "public"."aim_trainer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."countdown" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_character_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_platforms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_trials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_user_characters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_weapon_kill_counts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_weapon_perks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."destiny_weapons" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT ALL ON TABLE "public"."aim_trainer" TO "postgres";
GRANT ALL ON SEQUENCE "public"."aim_trainer_id_seq" TO "postgres";
GRANT ALL ON TABLE "public"."api_keys" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_character_types" TO "postgres";
GRANT ALL ON SEQUENCE "public"."character_types_id_seq" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_user_characters" TO "postgres";
GRANT ALL ON SEQUENCE "public"."characters_id_seq" TO "postgres";
GRANT ALL ON TABLE "public"."countdown" TO "postgres";
GRANT ALL ON SEQUENCE "public"."countdown_id_seq" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_platforms" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_trials" TO "postgres";
GRANT ALL ON SEQUENCE "public"."destiny_trials_id_seq" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_users" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_user_play_times" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_weapon_kill_counts" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_weapons" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_weapon_kill_summary" TO "postgres";
GRANT ALL ON TABLE "public"."destiny_weapon_perks" TO "postgres";
GRANT ALL ON SEQUENCE "public"."lesi_webhooks_id_seq" TO "postgres";
GRANT ALL ON TABLE "public"."terror_goal" TO "postgres";
GRANT ALL ON SEQUENCE "public"."terror_goal_id_seq" TO "postgres";
GRANT ALL ON TABLE "public"."terror_goal_messages" TO "postgres";
GRANT ALL ON TABLE "public"."user_profiles" TO "postgres";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."weapon_kill_counts_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."weapon_perks_id_seq" TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";

CREATE INDEX "idx_destiny_users_bungie_id_lower" ON "public"."destiny_users" USING "btree" ("lower"(("bungie_id")::"text"));
create index if not exists idx_destiny_user_characters_membership_id
    on public.destiny_user_characters (membership_id);
create index if not exists idx_destiny_weapon_kill_counts_membership_weapon_hash
    on public.destiny_weapon_kill_counts (membership_id, weapon_hash);
create index if not exists idx_destiny_weapon_kill_counts_membership_weapon_id
    on public.destiny_weapon_kill_counts (membership_id, weapon_id);
create index if not exists idx_destiny_weapon_kill_counts_weapon_hash
    on public.destiny_weapon_kill_counts (weapon_hash);
create index if not exists idx_destiny_weapons_bucket_type_hash
    on public.destiny_weapons (bucket_type_hash);





create table if not exists public.app_user (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),

  twitch_user_id text not null unique,
  twitch_login text not null,
  twitch_display_name text,
  twitch_avatar_url text
);
ALTER TABLE "public"."app_user" OWNER TO "postgres";
ALTER TABLE "public"."app_user" ENABLE ROW LEVEL SECURITY;

create table if not exists public.app_session (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_user(id) on delete cascade,
  session_token text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
ALTER TABLE "public"."app_session" OWNER TO "postgres";
ALTER TABLE "public"."app_session" ENABLE ROW LEVEL SECURITY;

create index if not exists app_session_user_id_idx on public.app_session(user_id);
create index if not exists app_session_expires_at_idx on public.app_session(expires_at);
