create schema if not exists music;

comment on schema music is 'Personal music scrobble data and Grafana reporting views';

create table if not exists music.artists (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  spotify_id text,
  url text,
  image_url text,
  constraint music_artists_name_not_blank check (btrim(name) <> ''),
  constraint music_artists_spotify_id_not_blank check (spotify_id is null or btrim(spotify_id) <> ''),
  constraint music_artists_url_http check (url is null or url ~* '^https?://'),
  constraint music_artists_image_url_http check (image_url is null or image_url ~* '^https?://')
);

create table if not exists music.albums (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  artist_id bigint not null references music.artists(id) on delete restrict,
  name text not null,
  spotify_id text,
  url text,
  image_url text,
  constraint music_albums_name_not_blank check (btrim(name) <> ''),
  constraint music_albums_spotify_id_not_blank check (spotify_id is null or btrim(spotify_id) <> ''),
  constraint music_albums_url_http check (url is null or url ~* '^https?://'),
  constraint music_albums_image_url_http check (image_url is null or image_url ~* '^https?://')
);

create table if not exists music.tracks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  artist_id bigint not null references music.artists(id) on delete restrict,
  album_id bigint references music.albums(id) on delete set null,
  name text not null,
  spotify_id text,
  url text,
  image_url text,
  constraint music_tracks_name_not_blank check (btrim(name) <> ''),
  constraint music_tracks_spotify_id_not_blank check (spotify_id is null or btrim(spotify_id) <> ''),
  constraint music_tracks_url_http check (url is null or url ~* '^https?://'),
  constraint music_tracks_image_url_http check (image_url is null or image_url ~* '^https?://')
);

create table if not exists music.scrobbles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  scrobbled_at timestamptz not null,
  artist_id bigint not null references music.artists(id) on delete restrict,
  album_id bigint references music.albums(id) on delete set null,
  track_id bigint not null references music.tracks(id) on delete restrict,
  source text not null default 'api',
  raw_payload jsonb not null default '{}'::jsonb,
  constraint music_scrobbles_source_not_blank check (btrim(source) <> '')
);

create unique index if not exists music_artists_spotify_id_uidx
on music.artists (spotify_id)
where spotify_id is not null;

create unique index if not exists music_artists_name_without_spotify_id_uidx
on music.artists (lower(name))
where spotify_id is null;

create unique index if not exists music_albums_spotify_id_uidx
on music.albums (spotify_id)
where spotify_id is not null;

create unique index if not exists music_albums_artist_name_without_spotify_id_uidx
on music.albums (artist_id, lower(name))
where spotify_id is null;

create unique index if not exists music_tracks_spotify_id_uidx
on music.tracks (spotify_id)
where spotify_id is not null;

create unique index if not exists music_tracks_artist_album_name_without_spotify_id_uidx
on music.tracks (artist_id, coalesce(album_id, 0), lower(name))
where spotify_id is null;

create unique index if not exists music_scrobbles_unique_play_uidx
on music.scrobbles (scrobbled_at, artist_id, track_id);

create index if not exists music_scrobbles_scrobbled_at_idx
on music.scrobbles (scrobbled_at desc);

create index if not exists music_scrobbles_artist_scrobbled_at_idx
on music.scrobbles (artist_id, scrobbled_at desc);

create index if not exists music_scrobbles_track_scrobbled_at_idx
on music.scrobbles (track_id, scrobbled_at desc);

create or replace view music.scrobble_events with (security_invoker = on) as
select
  s.id,
  extract(epoch from s.scrobbled_at)::bigint as uts,
  to_char(s.scrobbled_at at time zone 'UTC', 'DD Mon YYYY, HH24:MI') as utc_time,
  s.scrobbled_at,
  a.name as artist,
  a.spotify_id as artist_spotify_id,
  a.url as artist_url,
  a.image_url as artist_image_url,
  al.name as album,
  al.spotify_id as album_spotify_id,
  al.url as album_url,
  al.image_url as album_image_url,
  t.name as track,
  t.spotify_id as track_spotify_id,
  t.url as track_url,
  t.image_url as track_image_url,
  s.source,
  s.created_at,
  s.updated_at
from music.scrobbles s
join music.artists a on a.id = s.artist_id
join music.tracks t on t.id = s.track_id
left join music.albums al on al.id = s.album_id
order by s.scrobbled_at desc;

comment on table music.scrobbles is 'Personal music scrobble events for Grafana-backed listening history dashboards.';
comment on view music.scrobble_events is 'Flattened Last.fm-style scrobble rows for Grafana queries.';
