create table if not exists music.spotify_enrichment_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  entity_type text not null,
  entity_id bigint not null,
  status text not null,
  attempts integer not null default 0,
  confidence numeric(5, 4),
  spotify_id text,
  spotify_url text,
  image_url text,
  notes text,
  last_error text,
  searched_at timestamptz,
  constraint music_spotify_enrichment_entity_type_check
    check (entity_type in ('track', 'album', 'artist')),
  constraint music_spotify_enrichment_status_check
    check (status in ('matched', 'no_match', 'low_confidence', 'error', 'rate_limited')),
  constraint music_spotify_enrichment_attempts_check
    check (attempts >= 0),
  constraint music_spotify_enrichment_confidence_check
    check (confidence is null or (confidence >= 0 and confidence <= 1)),
  constraint music_spotify_enrichment_url_http
    check (spotify_url is null or spotify_url ~* '^https?://'),
  constraint music_spotify_enrichment_image_url_http
    check (image_url is null or image_url ~* '^https?://'),
  constraint music_spotify_enrichment_entity_unique
    unique (entity_type, entity_id)
);

create index if not exists music_spotify_enrichment_status_idx
on music.spotify_enrichment_attempts (entity_type, status, updated_at);

comment on table music.spotify_enrichment_attempts is 'Slow Spotify metadata enrichment attempt state for music artists, albums, and tracks.';
