create table if not exists music.genres (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  url text,
  constraint music_genres_name_not_blank check (btrim(name) <> ''),
  constraint music_genres_url_http check (url is null or url ~* '^https?://')
);

create unique index if not exists music_genres_lower_name_uidx
on music.genres (lower(name));

create table if not exists music.artist_genres (
  artist_id bigint not null references music.artists(id) on delete cascade,
  genre_id bigint not null references music.genres(id) on delete cascade,
  source text not null default 'lastfm',
  weight integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint music_artist_genres_source_not_blank check (btrim(source) <> ''),
  constraint music_artist_genres_weight_check check (weight is null or weight >= 0),
  primary key (artist_id, genre_id, source)
);

create table if not exists music.album_genres (
  album_id bigint not null references music.albums(id) on delete cascade,
  genre_id bigint not null references music.genres(id) on delete cascade,
  source text not null default 'lastfm',
  weight integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint music_album_genres_source_not_blank check (btrim(source) <> ''),
  constraint music_album_genres_weight_check check (weight is null or weight >= 0),
  primary key (album_id, genre_id, source)
);

create table if not exists music.track_genres (
  track_id bigint not null references music.tracks(id) on delete cascade,
  genre_id bigint not null references music.genres(id) on delete cascade,
  source text not null default 'lastfm',
  weight integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint music_track_genres_source_not_blank check (btrim(source) <> ''),
  constraint music_track_genres_weight_check check (weight is null or weight >= 0),
  primary key (track_id, genre_id, source)
);

create index if not exists music_artist_genres_genre_idx
on music.artist_genres (genre_id, artist_id);

create index if not exists music_album_genres_genre_idx
on music.album_genres (genre_id, album_id);

create index if not exists music_track_genres_genre_idx
on music.track_genres (genre_id, track_id);

create table if not exists music.lastfm_tag_enrichment_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  entity_type text not null,
  entity_id bigint not null,
  status text not null,
  attempts integer not null default 0,
  tags_found integer not null default 0,
  last_error text,
  searched_at timestamptz,
  constraint music_lastfm_tag_enrichment_entity_type_check
    check (entity_type in ('track', 'album', 'artist')),
  constraint music_lastfm_tag_enrichment_status_check
    check (status in ('tagged', 'no_tags', 'error', 'rate_limited', 'skipped')),
  constraint music_lastfm_tag_enrichment_attempts_check
    check (attempts >= 0),
  constraint music_lastfm_tag_enrichment_tags_found_check
    check (tags_found >= 0),
  constraint music_lastfm_tag_enrichment_entity_unique
    unique (entity_type, entity_id)
);

create index if not exists music_lastfm_tag_enrichment_status_idx
on music.lastfm_tag_enrichment_attempts (entity_type, status, updated_at);

create or replace view music.scrobble_events with (security_invoker = on) as
select
  s.id,
  extract(epoch from s.scrobbled_at)::bigint as uts,
  to_char(s.scrobbled_at at time zone 'UTC', 'DD Mon YYYY, HH24:MI') as utc_time,
  s.scrobbled_at,
  a.name as artist,
  a.spotify_id as artist_spotify_id,
  a.url as artist_url,
  a.image_url as artist_image_url,
  al.name as album,
  al.spotify_id as album_spotify_id,
  al.url as album_url,
  al.image_url as album_image_url,
  t.name as track,
  t.spotify_id as track_spotify_id,
  t.url as track_url,
  t.image_url as track_image_url,
  s.source,
  s.created_at,
  s.updated_at,
  coalesce(artist_tags.tags, '{}'::text[]) as artist_tags,
  coalesce(album_tags.tags, '{}'::text[]) as album_tags,
  coalesce(track_tags.tags, '{}'::text[]) as track_tags
from music.scrobbles s
join music.artists a on a.id = s.artist_id
join music.tracks t on t.id = s.track_id
left join music.albums al on al.id = s.album_id
left join lateral (
  select array_agg(g.name order by ag.weight desc nulls last, g.name) as tags
  from music.artist_genres ag
  join music.genres g on g.id = ag.genre_id
  where ag.artist_id = a.id
) artist_tags on true
left join lateral (
  select array_agg(g.name order by alg.weight desc nulls last, g.name) as tags
  from music.album_genres alg
  join music.genres g on g.id = alg.genre_id
  where alg.album_id = al.id
) album_tags on true
left join lateral (
  select array_agg(g.name order by tg.weight desc nulls last, g.name) as tags
  from music.track_genres tg
  join music.genres g on g.id = tg.genre_id
  where tg.track_id = t.id
) track_tags on true
order by s.scrobbled_at desc;

create or replace view music.top_played_songs with (security_invoker = on) as
select
  a.name as artist,
  al.name as album,
  t.name as track,
  count(*)::bigint as listened_count,
  min(s.scrobbled_at) as first_listened,
  max(s.scrobbled_at) as last_listened,
  t.url as track_url,
  coalesce(t.image_url, al.image_url) as track_art,
  coalesce(artist_tags.tags, '{}'::text[]) as artist_tags,
  coalesce(album_tags.tags, '{}'::text[]) as album_tags,
  coalesce(track_tags.tags, '{}'::text[]) as track_tags
from music.scrobbles s
join music.artists a on a.id = s.artist_id
join music.tracks t on t.id = s.track_id
left join music.albums al on al.id = s.album_id
left join lateral (
  select array_agg(g.name order by ag.weight desc nulls last, g.name) as tags
  from music.artist_genres ag
  join music.genres g on g.id = ag.genre_id
  where ag.artist_id = a.id
) artist_tags on true
left join lateral (
  select array_agg(g.name order by alg.weight desc nulls last, g.name) as tags
  from music.album_genres alg
  join music.genres g on g.id = alg.genre_id
  where alg.album_id = al.id
) album_tags on true
left join lateral (
  select array_agg(g.name order by tg.weight desc nulls last, g.name) as tags
  from music.track_genres tg
  join music.genres g on g.id = tg.genre_id
  where tg.track_id = t.id
) track_tags on true
group by
  a.id,
  a.name,
  al.id,
  al.name,
  al.image_url,
  t.id,
  t.name,
  t.url,
  t.image_url,
  artist_tags.tags,
  album_tags.tags,
  track_tags.tags
order by
  listened_count desc,
  last_listened desc,
  artist,
  track;

create or replace view music.top_played_albums with (security_invoker = on) as
select
  a.name as artist,
  al.name as album,
  count(*)::bigint as listened_count,
  min(s.scrobbled_at) as first_listened,
  max(s.scrobbled_at) as last_listened,
  al.url as album_url,
  al.image_url as album_art,
  coalesce(artist_tags.tags, '{}'::text[]) as artist_tags,
  coalesce(album_tags.tags, '{}'::text[]) as album_tags
from music.scrobbles s
join music.artists a on a.id = s.artist_id
join music.albums al on al.id = s.album_id
left join lateral (
  select array_agg(g.name order by ag.weight desc nulls last, g.name) as tags
  from music.artist_genres ag
  join music.genres g on g.id = ag.genre_id
  where ag.artist_id = a.id
) artist_tags on true
left join lateral (
  select array_agg(g.name order by alg.weight desc nulls last, g.name) as tags
  from music.album_genres alg
  join music.genres g on g.id = alg.genre_id
  where alg.album_id = al.id
) album_tags on true
group by
  a.id,
  a.name,
  al.id,
  al.name,
  al.url,
  al.image_url,
  artist_tags.tags,
  album_tags.tags
order by
  listened_count desc,
  last_listened desc,
  artist,
  album;

create or replace view music.top_played_artists with (security_invoker = on) as
select
  a.name as artist,
  count(*)::bigint as listened_count,
  min(s.scrobbled_at) as first_listened,
  max(s.scrobbled_at) as last_listened,
  a.url as artist_url,
  a.image_url as artist_art,
  coalesce(artist_tags.tags, '{}'::text[]) as artist_tags
from music.scrobbles s
join music.artists a on a.id = s.artist_id
left join lateral (
  select array_agg(g.name order by ag.weight desc nulls last, g.name) as tags
  from music.artist_genres ag
  join music.genres g on g.id = ag.genre_id
  where ag.artist_id = a.id
) artist_tags on true
group by
  a.id,
  a.name,
  a.url,
  a.image_url,
  artist_tags.tags
order by
  listened_count desc,
  last_listened desc,
  artist;

comment on table music.genres is 'Last.fm genre/tag labels for music reporting.';
comment on table music.artist_genres is 'Artist-to-tag relationships sourced from Last.fm top tags.';
comment on table music.album_genres is 'Album-to-tag relationships sourced from Last.fm top tags.';
comment on table music.track_genres is 'Track-to-tag relationships sourced from Last.fm top tags.';
comment on table music.lastfm_tag_enrichment_attempts is 'Last.fm tag lookup attempt state for music artists, albums, and tracks.';

create index if not exists music_scrobbles_album_scrobbled_at_idx
on music.scrobbles (album_id, scrobbled_at desc)
where album_id is not null;
