create table if not exists public.request_capture (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null,
  ip text not null default '',
  user_agent text not null default '',
  content_type text not null default '',
  content_length bigint not null default 0,
  headers jsonb not null default '{}'::jsonb,
  body jsonb not null
);

create index if not exists request_capture_created_at_idx
on public.request_capture (created_at desc);
