

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  insert into public.user_profiles (user_id)
  values (new.id);
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."aim_trainer" (
    "id" bigint NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "username" "text" DEFAULT ''::"text" NOT NULL,
    "score" real DEFAULT '0'::real,
    "accuracy" real DEFAULT '0'::real,
    "completed_rounds" integer,
    "milo_attacks" integer,
    "nice_triggers" integer
);


ALTER TABLE "public"."aim_trainer" OWNER TO "postgres";


ALTER TABLE "public"."aim_trainer" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."aim_trainer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."api_keys" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "access_token" "text",
    "refresh_token" "text",
    "refresh_token_expiry" bigint,
    "client_id" "text",
    "client_secret" "text",
    "base_url" "text",
    "redirect_url" "text"
);


ALTER TABLE "public"."api_keys" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_character_types" (
    "id" bigint NOT NULL,
    "character_type" character varying NOT NULL,
    "bungie_character_type_id" smallint
);


ALTER TABLE "public"."destiny_character_types" OWNER TO "postgres";


ALTER TABLE "public"."destiny_character_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."character_types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."destiny_user_characters" (
    "id" bigint NOT NULL,
    "membership_id" character varying NOT NULL,
    "character_id" character varying NOT NULL,
    "character_type" character varying,
    "minutes_played" bigint
);


ALTER TABLE "public"."destiny_user_characters" OWNER TO "postgres";


ALTER TABLE "public"."destiny_user_characters" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."characters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."countdown" (
    "id" bigint NOT NULL,
    "uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "target_date" timestamp with time zone NOT NULL,
    "message" "text" NOT NULL,
    "fallback_message" "text" NOT NULL
);


ALTER TABLE "public"."countdown" OWNER TO "postgres";


ALTER TABLE "public"."countdown" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."countdown_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."destiny_platforms" (
    "platform_id" smallint NOT NULL,
    "platform_friendly_name" character varying
);


ALTER TABLE "public"."destiny_platforms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_trials" (
    "id" bigint NOT NULL,
    "map" "text" NOT NULL,
    "loot" "text" NOT NULL,
    "start_date" timestamp without time zone NOT NULL,
    "end_date" timestamp without time zone NOT NULL,
    "week_number" bigint NOT NULL
);


ALTER TABLE "public"."destiny_trials" OWNER TO "postgres";


ALTER TABLE "public"."destiny_trials" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."destiny_trials_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."destiny_users" (
    "id" bigint NOT NULL,
    "membership_id" character varying,
    "bungie_id" character varying,
    "preferred_platform" smallint,
    "friendly_name" character varying
);


ALTER TABLE "public"."destiny_users" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."destiny_user_play_times" WITH ("security_invoker"='on') AS
 SELECT "u"."bungie_id",
    "sum"(
        CASE
            WHEN (("c"."character_type")::"text" = 'Warlock'::"text") THEN "c"."minutes_played"
            ELSE (0)::bigint
        END) AS "total_warlock_minutes",
    "sum"(
        CASE
            WHEN (("c"."character_type")::"text" = 'Hunter'::"text") THEN "c"."minutes_played"
            ELSE (0)::bigint
        END) AS "total_hunter_minutes",
    "sum"(
        CASE
            WHEN (("c"."character_type")::"text" = 'Titan'::"text") THEN "c"."minutes_played"
            ELSE (0)::bigint
        END) AS "total_titan_minutes"
   FROM ("public"."destiny_user_characters" "c"
     JOIN "public"."destiny_users" "u" ON ((("u"."membership_id")::"text" = ("c"."membership_id")::"text")))
  GROUP BY "u"."bungie_id";


ALTER TABLE "public"."destiny_user_play_times" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_weapon_kill_counts" (
    "id" bigint NOT NULL,
    "membership_id" character varying,
    "weapon_id" character varying,
    "pvp_kills" bigint,
    "pve_kills" bigint,
    "trials_kills" bigint,
    "weapon_hash" "text"
);


ALTER TABLE "public"."destiny_weapon_kill_counts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_weapons" (
    "id" "text" NOT NULL,
    "display_name" "text",
    "item_type_display_name" "text",
    "flavor_text" "text",
    "bucket_type_hash" "text",
    "tier_type_hash" "text",
    "tier_type_name" "text",
    "tier_type" integer,
    "talent_grid_hash" "text"
);


ALTER TABLE "public"."destiny_weapons" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."destiny_weapon_kill_summary" WITH ("security_invoker"='on') AS
 SELECT "u"."bungie_id",
    "w"."display_name" AS "weapon_name",
    "wkc"."pvp_kills",
    "wkc"."pve_kills",
    "wkc"."trials_kills"
   FROM (("public"."destiny_weapon_kill_counts" "wkc"
     JOIN "public"."destiny_users" "u" ON ((("u"."membership_id")::"text" = ("wkc"."membership_id")::"text")))
     JOIN "public"."destiny_weapons" "w" ON (("w"."id" = "wkc"."weapon_hash")))
  WHERE (1 = 1)
  ORDER BY ("wkc"."pvp_kills" IS NULL), "wkc"."pvp_kills" DESC, "u"."bungie_id";


ALTER TABLE "public"."destiny_weapon_kill_summary" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."destiny_weapon_perks" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "item_type" "text",
    "hash_id" "text" NOT NULL
);


ALTER TABLE "public"."destiny_weapon_perks" OWNER TO "postgres";


ALTER TABLE "public"."api_keys" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."lesi_webhooks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."terror_goal" (
    "id" bigint NOT NULL,
    "message" "text"
);


ALTER TABLE "public"."terror_goal" OWNER TO "postgres";


ALTER TABLE "public"."terror_goal" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."terror_goal_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."terror_goal_messages" WITH ("security_invoker"='on') AS
 SELECT "g"."message"
   FROM "public"."terror_goal" "g"
  GROUP BY "g"."message"
  ORDER BY ("max"("g"."id")) DESC
 LIMIT 5;


ALTER TABLE "public"."terror_goal_messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "user_id" "uuid" NOT NULL,
    "youtube_access_token" "text",
    "youtube_refresh_token" "text",
    "youtube_token_expires_at" timestamp with time zone,
    "instagram_access_token" "text",
    "instagram_refresh_token" "text",
    "instagram_token_expires_at" timestamp with time zone,
    "tiktok_access_token" "text",
    "tiktok_refresh_token" "text",
    "tiktok_token_expires_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "tiktok_open_id" "text"
);


ALTER TABLE "public"."user_profiles" OWNER TO "postgres";


ALTER TABLE "public"."destiny_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."destiny_weapon_kill_counts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."weapon_kill_counts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."destiny_weapon_perks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."weapon_perks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."aim_trainer"
    ADD CONSTRAINT "aim_trainer_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."aim_trainer"
    ADD CONSTRAINT "aim_trainer_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."destiny_character_types"
    ADD CONSTRAINT "character_types_bungie_character_type_id_key" UNIQUE ("bungie_character_type_id");



ALTER TABLE ONLY "public"."destiny_character_types"
    ADD CONSTRAINT "character_types_character_type_key" UNIQUE ("character_type");



ALTER TABLE ONLY "public"."destiny_character_types"
    ADD CONSTRAINT "character_types_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "characters_character_id_key" UNIQUE ("character_id");



ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "characters_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."countdown"
    ADD CONSTRAINT "countdown_pkey" PRIMARY KEY ("id", "uuid");



ALTER TABLE ONLY "public"."destiny_trials"
    ADD CONSTRAINT "destiny_trials_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."destiny_trials"
    ADD CONSTRAINT "destiny_trials_week_number_key" UNIQUE ("week_number");



ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "lesi_webhooks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."destiny_platforms"
    ADD CONSTRAINT "platforms_pkey" PRIMARY KEY ("platform_id");



ALTER TABLE ONLY "public"."destiny_platforms"
    ADD CONSTRAINT "platforms_platform_id_key" UNIQUE ("platform_id");



ALTER TABLE ONLY "public"."terror_goal"
    ADD CONSTRAINT "terror_goal_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "unique_membership_bungie" UNIQUE ("membership_id", "bungie_id");



ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "unique_membership_character" UNIQUE ("membership_id", "character_id");



ALTER TABLE ONLY "public"."destiny_weapon_kill_counts"
    ADD CONSTRAINT "unique_membership_weapon" UNIQUE ("membership_id", "weapon_id");



ALTER TABLE ONLY "public"."destiny_weapon_kill_counts"
    ADD CONSTRAINT "unique_user_weapon_pair" UNIQUE ("membership_id", "weapon_id");



ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_bungie_id_key" UNIQUE ("bungie_id");



ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_membership_id_key" UNIQUE ("membership_id");



ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."destiny_weapon_kill_counts"
    ADD CONSTRAINT "weapon_kill_counts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."destiny_weapon_perks"
    ADD CONSTRAINT "weapon_perks_hash_id_key" UNIQUE ("hash_id");



ALTER TABLE ONLY "public"."destiny_weapon_perks"
    ADD CONSTRAINT "weapon_perks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."destiny_weapons"
    ADD CONSTRAINT "weapons_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_destiny_users_bungie_id_lower" ON "public"."destiny_users" USING "btree" ("lower"(("bungie_id")::"text"));



CREATE OR REPLACE TRIGGER "set_updated_at" BEFORE UPDATE ON "public"."user_profiles" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."destiny_user_characters"
    ADD CONSTRAINT "characters_character_type_fkey" FOREIGN KEY ("character_type") REFERENCES "public"."destiny_character_types"("character_type");



ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."destiny_users"
    ADD CONSTRAINT "users_preferred_platform_fkey" FOREIGN KEY ("preferred_platform") REFERENCES "public"."destiny_platforms"("platform_id") ON UPDATE RESTRICT;



CREATE POLICY "Allow individual access to own profile" ON "public"."user_profiles" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Enable read access for service role" ON "public"."api_keys" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable read access for service role" ON "public"."destiny_character_types" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable read access for service role" ON "public"."destiny_platforms" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable read access for service role" ON "public"."destiny_user_characters" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable read access for service role" ON "public"."destiny_users" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable read access for service role" ON "public"."destiny_weapon_kill_counts" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable read access for service role" ON "public"."destiny_weapon_perks" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable read access for service role" ON "public"."destiny_weapons" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Enable update access for service role" ON "public"."api_keys" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for service role" ON "public"."destiny_character_types" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for service role" ON "public"."destiny_platforms" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for service role" ON "public"."destiny_user_characters" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for service role" ON "public"."destiny_users" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for service role" ON "public"."destiny_weapon_kill_counts" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for service role" ON "public"."destiny_weapon_perks" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable update access for service role" ON "public"."destiny_weapons" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."api_keys" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."destiny_character_types" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."destiny_platforms" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."destiny_user_characters" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."destiny_users" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."destiny_weapon_kill_counts" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."destiny_weapon_perks" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Enable write access for service role" ON "public"."destiny_weapons" FOR INSERT TO "service_role" WITH CHECK (true);



ALTER TABLE "public"."aim_trainer" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."api_keys" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."countdown" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_character_types" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_platforms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_trials" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_user_characters" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_weapon_kill_counts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_weapon_perks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."destiny_weapons" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "insert_user_profiles_public" ON "public"."user_profiles" FOR INSERT WITH CHECK (true);



ALTER TABLE "public"."terror_goal" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_profiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."aim_trainer" TO "anon";
GRANT ALL ON TABLE "public"."aim_trainer" TO "authenticated";
GRANT ALL ON TABLE "public"."aim_trainer" TO "service_role";



GRANT ALL ON SEQUENCE "public"."aim_trainer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."aim_trainer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."aim_trainer_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."api_keys" TO "anon";
GRANT ALL ON TABLE "public"."api_keys" TO "authenticated";
GRANT ALL ON TABLE "public"."api_keys" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_character_types" TO "anon";
GRANT ALL ON TABLE "public"."destiny_character_types" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_character_types" TO "service_role";



GRANT ALL ON SEQUENCE "public"."character_types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."character_types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."character_types_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_user_characters" TO "anon";
GRANT ALL ON TABLE "public"."destiny_user_characters" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_user_characters" TO "service_role";



GRANT ALL ON SEQUENCE "public"."characters_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."characters_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."characters_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."countdown" TO "anon";
GRANT ALL ON TABLE "public"."countdown" TO "authenticated";
GRANT ALL ON TABLE "public"."countdown" TO "service_role";



GRANT ALL ON SEQUENCE "public"."countdown_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."countdown_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."countdown_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_platforms" TO "anon";
GRANT ALL ON TABLE "public"."destiny_platforms" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_platforms" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_trials" TO "anon";
GRANT ALL ON TABLE "public"."destiny_trials" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_trials" TO "service_role";



GRANT ALL ON SEQUENCE "public"."destiny_trials_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."destiny_trials_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."destiny_trials_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_users" TO "anon";
GRANT ALL ON TABLE "public"."destiny_users" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_users" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_user_play_times" TO "anon";
GRANT ALL ON TABLE "public"."destiny_user_play_times" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_user_play_times" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_weapon_kill_counts" TO "anon";
GRANT ALL ON TABLE "public"."destiny_weapon_kill_counts" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_weapon_kill_counts" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_weapons" TO "anon";
GRANT ALL ON TABLE "public"."destiny_weapons" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_weapons" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_weapon_kill_summary" TO "anon";
GRANT ALL ON TABLE "public"."destiny_weapon_kill_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_weapon_kill_summary" TO "service_role";



GRANT ALL ON TABLE "public"."destiny_weapon_perks" TO "anon";
GRANT ALL ON TABLE "public"."destiny_weapon_perks" TO "authenticated";
GRANT ALL ON TABLE "public"."destiny_weapon_perks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."lesi_webhooks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."lesi_webhooks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."lesi_webhooks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."terror_goal" TO "anon";
GRANT ALL ON TABLE "public"."terror_goal" TO "authenticated";
GRANT ALL ON TABLE "public"."terror_goal" TO "service_role";



GRANT ALL ON SEQUENCE "public"."terror_goal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."terror_goal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."terror_goal_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."terror_goal_messages" TO "anon";
GRANT ALL ON TABLE "public"."terror_goal_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."terror_goal_messages" TO "service_role";



GRANT ALL ON TABLE "public"."user_profiles" TO "anon";
GRANT ALL ON TABLE "public"."user_profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."weapon_kill_counts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."weapon_kill_counts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."weapon_kill_counts_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."weapon_perks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."weapon_perks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."weapon_perks_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


